const fs = require('node:fs');
const path = require('node:path');

const root = __dirname;
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const version = packageJson.version;
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'adapters/manifest.json'), 'utf8'));
const files = ['api.js', 'adapter-utils.js', 'player.js', 'ui.js', 'settings.js', 'core.js']
  .concat(manifest.adapters.filter((entry) => entry.enabled !== false).map((entry) => entry.module));
const banner = `/* SisiPlus v${version} — single-file build for Lampa. Generated by build.cjs. */\n`;
const body = files.map((file) => `\n/* ===== ${file} ===== */\n${fs.readFileSync(path.join(root, file), 'utf8').trim()}\n`).join('');
const open = `(function sisiplusBundle(window){\n'use strict';\nif(window.__sisiplusBundleStarted) return;\nwindow.__sisiplusBundleStarted = true;\nwindow.SisiPlusVersion = '${version}';\n`;
const boot = `\nif(window.SisiPlus) window.SisiPlus.boot();\n})(window);\n`;
fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.writeFileSync(path.join(root, 'dist', 'sisiplus.js'), banner + open + body + boot, 'utf8');
console.log(`Built dist/sisiplus.js from ${files.length} modules`);
